require(ggplot2)
library(scales)

 ggplot(survey, aes(x= as.factor(Student))) + geom_bar(width = 0.2,aes(fill=factor(Student))) + coord_flip()  + stat_count(aes(label = paste(prop.table(..count..) * 100, "%", sep = "")),
                                                                                                                                   vjust = 1, geom = "text", position = "identity", color ="white") + theme_minimal()
# ggplot(survey, aes(x= as.factor(Country))) + geom_bar() + coord_flip()
 ggplot(survey, aes(x= as.factor(AssessJob1))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob1))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob2))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob2))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob3))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob3))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob4))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob4))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob5))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob5))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob6))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob6))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob7))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob7))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob8))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob8))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob9))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob9))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessJob10))) + geom_bar(width = 0.2,aes(fill=factor(AssessJob10))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits1))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits1))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits2))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits2))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits3))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits3))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits4))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits4))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits5))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits5))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits6))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits6))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits7))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits7))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits8))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits8))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits9))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits9))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits10))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits10))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AssessBenefits11))) + geom_bar(width = 0.2,aes(fill=factor(AssessBenefits11))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobContactPriorities1))) + geom_bar(width = 0.2,aes(fill=factor(JobContactPriorities1))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobContactPriorities2))) + geom_bar(width = 0.2,aes(fill=factor(JobContactPriorities2))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobContactPriorities3))) + geom_bar(width = 0.2,aes(fill=factor(JobContactPriorities3))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobContactPriorities4))) + geom_bar(width = 0.2,aes(fill=factor(JobContactPriorities4))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobContactPriorities5))) + geom_bar(width = 0.2,aes(fill=factor(JobContactPriorities5))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobEmailPriorities1))) + geom_bar(width = 0.2,aes(fill=factor(JobEmailPriorities1))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobEmailPriorities2))) + geom_bar(width = 0.2,aes(fill=factor(JobEmailPriorities2))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobEmailPriorities3))) + geom_bar(width = 0.2,aes(fill=factor(JobEmailPriorities3))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobEmailPriorities4))) + geom_bar(width = 0.2,aes(fill=factor(JobEmailPriorities4))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobEmailPriorities5))) + geom_bar(width = 0.2,aes(fill=factor(JobEmailPriorities5))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobEmailPriorities6))) + geom_bar(width = 0.2,aes(fill=factor(JobEmailPriorities6))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobEmailPriorities7))) + geom_bar(width = 0.2,aes(fill=factor(JobEmailPriorities7))) + coord_flip() + theme_minimal()
 
 ggplot(survey, aes(x= as.factor(OpenSource))) + geom_bar(aes(fill=factor(OpenSource)),width = 0.2) + coord_flip() + theme_minimal() + 
 ggplot(survey, aes(x= as.factor(Hobby))) + geom_bar(width = 0.2,aes(fill=factor(Hobby))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(UndergradMajor))) + geom_bar(aes(fill=factor(UndergradMajor))) + coord_flip() + theme_minimal()
 #ggplot(survey, aes(x= as.factor(DevType))) + geom_bar() + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(YearsCoding))) + geom_bar(aes(fill=factor(YearsCoding))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobSatisfaction))) + geom_bar(aes(fill=factor(JobSatisfaction))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(CareerSatisfaction))) + geom_bar(aes(fill=factor(CareerSatisfaction))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(HopeFiveYears))) + geom_bar(aes(fill=factor(HopeFiveYears))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(JobSearchStatus))) + geom_bar(aes(fill=factor(JobSearchStatus)), width = 0.7) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(LastNewJob))) + geom_bar(aes(fill=factor(LastNewJob))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(UpdateCV))) + geom_bar(aes(fill=factor(UpdateCV))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(Currency))) + geom_bar(aes(fill=factor(Currency))) + coord_flip() + theme_minimal()
# ggplot(survey, aes(x= as.factor(CommunicationTools))) + geom_bar() + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(TimeFullyProductive))) + geom_bar(aes(fill=factor(TimeFullyProductive))) + coord_flip() + theme_minimal()
 #ggplot(survey, aes(x= as.factor(EducationTypes))) + geom_bar() + coord_flip() + theme_minimal()
# ggplot(survey, aes(x= as.factor(SelfTaughtTypes))) + geom_bar() + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(TimeAfterBootcamp))) + geom_bar(aes(fill=factor(TimeAfterBootcamp))) + coord_flip() + theme_minimal()
 #ggplot(survey, aes(x= as.factor(HackathonReasons))) + geom_bar() + coord_flip() + theme_minimal()
# ggplot(survey, aes(x= as.factor(LanguageWorkedWith))) + geom_bar() + coord_flip() + theme_minimal()
# ggplot(survey, aes(x= as.factor(DatabaseWorkedWith))) + geom_bar() + coord_flip() + theme_minimal()
 #ggplot(survey, aes(x= as.factor(FrameworkWorkedWith))) + geom_bar() + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(OperatingSystem))) + geom_bar(aes(fill=factor(OperatingSystem))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(NumberMonitors))) + geom_bar(aes(fill=factor(NumberMonitors))) + coord_flip() + theme_minimal()
# ggplot(survey, aes(x= as.factor(Methodology))) + geom_bar() + coord_flip() + theme_minimal() 
# ggplot(survey, aes(x= as.factor(VersionControl))) + geom_bar() + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(CheckInCode))) + geom_bar(aes(fill=factor(CheckInCode))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdBlocker))) + geom_bar(aes(fill=factor(AdBlocker))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdBlockerDisable))) + geom_bar(aes(fill=factor(AdBlockerDisable))) + coord_flip() + theme_minimal()
# ggplot(survey, aes(x= as.factor(AdsActions))) + geom_bar() + coord_flip + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdsPriorities1))) + geom_bar(width = 0.2,aes(fill=factor(AdsPriorities1))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdsPriorities2))) + geom_bar(width = 0.2,aes(fill=factor(AdsPriorities2))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdsPriorities3))) + geom_bar(width = 0.2,aes(fill=factor(AdsPriorities3))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdsPriorities4))) + geom_bar(width = 0.2,aes(fill=factor(AdsPriorities4))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdsPriorities5))) + geom_bar(width = 0.2,aes(fill=factor(AdsPriorities5))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdsPriorities6))) + geom_bar(width = 0.2,aes(fill=factor(AdsPriorities6))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(AdsPriorities7))) + geom_bar(width = 0.2,aes(fill=factor(AdsPriorities7))) + coord_flip() + theme_minimal()
 
 ggplot(survey, aes(x= as.factor(EthicsChoice))) + geom_bar(aes(fill=factor(EthicsChoice))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(EthicsResponsible))) + geom_bar(aes(fill=factor(EthicsResponsible))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(StackOverflowVisit))) + geom_bar(aes(fill=factor(StackOverflowVisit))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(StackOverflowParticipate))) + geom_bar(aes(fill=factor(StackOverflowParticipate))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(StackOverflowHasAccount))) + geom_bar(aes(fill=factor(StackOverflowHasAccount))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(StackOverflowJobs))) + geom_bar(aes(fill=factor(StackOverflowJobs))) + coord_flip()+ theme_minimal()
 ggplot(survey, aes(x= as.factor(StackOverflowConsiderMember))) + geom_bar(aes(fill=factor(StackOverflowConsiderMember))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(StackOverflowParticipate))) + geom_bar(aes(fill=factor(StackOverflowParticipate))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(HypotheticalTools1))) + geom_bar(aes(fill=factor(HypotheticalTools1))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(HypotheticalTools2))) + geom_bar(aes(fill=factor(HypotheticalTools2))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(HypotheticalTools3))) + geom_bar(aes(fill=factor(HypotheticalTools3))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(HypotheticalTools4))) + geom_bar(aes(fill=factor(HypotheticalTools4))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(HypotheticalTools5))) + geom_bar(aes(fill=factor(HypotheticalTools5))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(HoursComputer))) + geom_bar(aes(fill=factor(HoursComputer))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(HoursOutside))) + geom_bar(aes(fill=factor(HoursOutside))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(SkipMeals))) + geom_bar(aes(fill=factor(SkipMeals))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(Exercise))) + geom_bar(aes(fill=factor(Exercise))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(Gender))) + geom_bar(aes(fill=factor(Gender))) + coord_flip() + theme_minimal()
# ggplot(survey, aes(x= as.factor(RaceEthnicity))) + geom_bar() + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(Dependents))) + geom_bar(aes(fill=factor(Dependents))) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(MilitaryUS))) + geom_bar(aes(fill=factor(MilitaryUS)),width = 0.5) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(SurveyTooLong))) + geom_bar(aes(fill=factor(SurveyTooLong)),width = 0.5) + coord_flip() + theme_minimal()
 ggplot(survey, aes(x= as.factor(SurveyEasy))) + geom_bar(aes(fill=factor(SurveyEasy))) + coord_flip() + theme_light()
 